sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get -y --no-install-recommends install texlive-full
  - sudo mkdir -p /usr/share/fonts/truetype
  - sudo cp font/* /usr/share/fonts/truetype
  - sudo mkfontscale
  - sudo mkfontdir
  - sudo fc-cache -fv

before_script:
  - sed -i 's/\[RawFeature={vertical:}\]{FangSong}/\[Extension=.otf,RawFeature={vertical:}\]{FandolFang-Regular}/' shuji.tex

script:
  - xelatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf main.tex
  - bibtex main.aux
  - xelatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf main.tex
  - xelatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf main.tex
